### ISSUE TITLE
Bounding Box Issue 

### ISSUE THREAD

**Issue by Deio828** [AlanNaoto/carla-dataset-runner#3]
Thank you really for this great project which has helped me alot in my graduation project 
I just had some issue in the output, I did exactly as described in the README file but the output bounding box in the hdf5 file is always an array of [-1, -1, -1, -1] even if there was a vehicle or a walker in the taken frame. What may cause such a problem?
Thanks in advance

**Comment by AlanNaoto** [comment]
Hey there! Really glad it was of help for your graduation. 

The [-1, -1, -1, -1] value is assigned when any of the several given conditions in the function filter_bounding_boxes of the bb_filter.py file are met. I basically check for a lot of hand-crafted conditions, and if one of them is true, then [-1, -1, -1, -1] will be returned:
- [if the bounding box is stretching too far away from the camera view](https://github.com/AlanNaoto/carla-dataset-runner/blob/3477d6b1660219e606f6376c302618d0e1706537/bb_filter.py#L32-L40)
- [if the bounding box is too far away, making it too small](https://github.com/AlanNaoto/carla-dataset-runner/blob/3477d6b1660219e606f6376c302618d0e1706537/bb_filter.py#L50-L54)
- [if at least 50% of the bounding box area is occluded](https://github.com/AlanNaoto/carla-dataset-runner/blob/3477d6b1660219e606f6376c302618d0e1706537/bb_filter.py#L209-L212)

These conditions were created so that I would not create labeled data in my dataset which had too little valuable information for training machine learning models. You can try debugging your code around these lines to see if the proposed bounding boxes are being eliminated. 

Please let me know if that helped.
Cheers

**Comment by Deio828** [comment]
Thank you, I have edited the filter to have a 3D bounding box for all actors in the scene and your reply helped me a lot

**Comment by AlanNaoto** [comment]
Nice! I'm happy that it is working for you. I'm closing this issue now then.
